### PR TITLE
Enable GitHub actions

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by superm1** [comment]
> E: Unable to locate package libgnutls30-dev

I think you might want libgnutls28-dev

**Comment by hughsie** [comment]
> I think you might want libgnutls28-dev

We depend on a newer GnuTLS unfortunately. I think waiting the 16 days for the Ubuntu focal release is probably the easiest way to fix this, rather than adding random PPAs and workarounds.

**Comment by superm1** [comment]
> > I think you might want libgnutls28-dev
> 
> We depend on a newer GnuTLS unfortunately. I think waiting the 16 days for the Ubuntu focal release is probably the easiest way to fix this, rather than adding random PPAs and workarounds.

It looks to me like the binary package `libgnutls28-dev` will depend on `libgnutls30`.  Are you sure this is not the one you want?
https://launchpad.net/ubuntu/+source/gnutls28/3.6.11.1-2ubuntu2/+build/18564333

**Comment by hughsie** [comment]
>  Are you sure this is not the one you want

Ya, but still

    meson.build:137:2: ERROR: Invalid version of dependency, need 'gnutls' ['>= 3.6.0'] found '3.5.18'.

Zygmunt Krynicki has built me a PPA that might work. Trying that now.

**Comment by superm1** [comment]
> > Are you sure this is not the one you want
> 
> Ya, but still
> 
> ```
> meson.build:137:2: ERROR: Invalid version of dependency, need 'gnutls' ['>= 3.6.0'] found '3.5.18'.
> ```
> 
> Zygmunt Krynicki has built me a PPA that might work. Trying that now.

Oh... You're building from bionic then not from focal.
```
    runs-on: ubuntu-latest
```

Doesn't really mean ubuntu-latest.  It means latest LTS.

**Comment by superm1** [comment]
> > > Are you sure this is not the one you want
> > 
> > 
> > Ya, but still
> > ```
> > meson.build:137:2: ERROR: Invalid version of dependency, need 'gnutls' ['>= 3.6.0'] found '3.5.18'.
> > ```
> > 
> > 
> > Zygmunt Krynicki has built me a PPA that might work. Trying that now.
> 
> Oh... You're building from bionic then not from focal.
> 
> ```
>     runs-on: ubuntu-latest
> ```
> 
> Doesn't really mean ubuntu-latest. It means latest LTS.

And that seems to match what https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners sees too.  I anticipate that even after 20.04 gets released they probably need some cycles to get it supported in case of any differences.

To prevent breaking it when that they _do_ start supporting 20.04 I would recommend you switch `ubuntu-latest` to `ubuntu-18.04`.

**Comment by hughsie** [comment]
> I would recommend you switch ubuntu-latest to ubuntu-18.04.

Done! I'm still not 100% sure why travis results are not showing up here; the builds get created but they don't register as "checks" in the PR.

**Pull request merged**
