### PR TITLE
trivial: don't install `jcat-self-test` to filesystem

### PR DESCRIPTION
**Pull request by superm1**

### CODE REVIEW

**Comment by hughsie** [comment]
Don't we need it to make the installed tests work?

**Comment by superm1** [comment]
But it's not actually an installed test.  It's just unit tests to run at the end of build?  Or did I get it wrong?

**Comment by hughsie** [comment]
Try `gnome-desktop-testing-runner libjcat` when you've installed it systemwide.

**Comment by hughsie** [comment]
https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests

**Comment by superm1** [comment]
Ah I see, OK thanks!

**Pull request closed without merging**
